#THINGS TO WORK ON
#1. SOLUTION RUNS ON THE ASSUMPTION THAT THE PAPER SIZE ENTERED IS ACCORDING TO THE SIZE OF PAPER SPACE (SHALL BE MODIFIED TO SCAN FOR PAPER SPACE AND SET THE SAME ACCORDINGLY) 
#2. Use Customized Template
#3. Import Template from other document


#NOTES:
#ActiveLayout Iterates in Alphabatical order


from pyautocad import Autocad, APoint, aDouble, aInt

acad = Autocad(create_if_not_exists=True)


def empty_paperspace():
    for i in acad.doc.Layouts:
        acad.doc.ActiveLayout = i  
        for j in acad.doc.PaperSpace:
                j.Delete()
    acad.doc.Regen
#CREATE LAYOUTS: Get user input for (Layout Series Name and Number of Layouts)
def create_layouts(initial: str, numbers: int, ):
    for i in range(0, numbers):
        name = initial + str(i+1)
        acad.doc.Layouts.Add(name)
    layouts=[]
    #Delete the default layouts
    for i in acad.doc.Layouts:
        if i.Name == "Layout1" or i.Name == "Layout2":
            print(i.Name)
            i.Delete()
        else:
            layouts.append(i)
        continue
    print(layouts)
    return layouts

def turn_on_viewport(viewport):
    viewport.ViewportOn = True
    print("Viewport On: " + str(viewport.ViewportOn))   #Important

def create_a_view(name: str):
    v = acad.doc.Views.Add(name)
    print("View name: " + v.Name + " is created.")
    print("=======================================")
    v.Center = aDouble(4343.5, 3901)
    return v

def toggle_model_paper(space: int):
    acad.doc.ActiveSpace = space                  #0 = acPaperSpace, 1 = acModelSpace
    print(acad.doc.ActiveSpace)
    
def generate_layouts(layout_list: list):
    if acad.doc.ActiveSpace != 0:
        toggle_model_paper(0)
    Initial_Center = [600, 370]                         #Take/Generate as Input w.r.t. LAYER
    Initial_LL = [0, 0, 0]                              #Take/Generate as Input w.r.t. LAYER
    Initial_UR = [1200, 700, 0]                         #Take/Generate as Input w.r.t. LAYER
    Spacing = 1200                                      #Take/Generate as Input w.r.t. LAYER (No need if layer is present)
    j = 0
    for i in range(len(layout_list)):
        if layout_list[i].Name != 'Model':
            
            acad.doc.ActiveLayout = layout_list[i]                   #Activate Layout

            view_name = 'view-' + str(j)
            v1 = acad.doc.Views.Add(view_name)
            v1.Center = aDouble(Initial_Center)           #Take autogenerated values as input
            Initial_Center[0]+=Spacing

            pv1 = acad.doc.PaperSpace.AddPViewport(aDouble(143.383, 99.9067, 0), 286.766, 199.8133) #Input autogenerated inputs from the CanonicalMediaName
            turn_on_viewport(pv1)

            if acad.doc.MSpace == False:
                pv1.Display(True)
                acad.doc.MSpace = True

            acad.doc.ActivePViewport = pv1
            
            acad.app.ZoomWindow(APoint(Initial_LL), APoint(Initial_UR))
            Initial_LL[0]+=Spacing
            Initial_UR[0]+=Spacing


l1 = create_layouts('elev-', 3)
empty_paperspace()
generate_layouts(l1)